### ISSUE TITLE
issues when get the result

### ISSUE THREAD

**Issue by OnlyFlashEobard** [lukas-blecher/Deep-Flow-Guided-Video-Inpainting#10]
thanks for cv2 detail,I had solve it but after that i get a new problem.

here are error details:
(lpz) mobax@nvidia-quadro-vws-ubuntu-18-1-vm:~/lpz/Deep-Flow-Guided-Video-Inpainting-master$ python tools/video_inpaint.py --frame_dir ./demo/frames --MASK_ROOT ./demo/masks --img_size 512 832 --LiteFlowNet --DFC --ResNet101 --Propagation
This Video has 80 Images
The optical flow list has been generated: ./demo/video_flow.txt
====> Loading ./pretrained_models/sintel.pth
Traceback (most recent call last):
  File "tools/video_inpaint.py", line 185, in <module>
    main()
  File "tools/video_inpaint.py", line 166, in main
    extract_flow(args)
  File "tools/video_inpaint.py", line 85, in extract_flow
    output_file = infer(args)
  File "/home/mobax/lpz/Deep-Flow-Guided-Video-Inpainting-master/tools/infer_liteflownet.py", line 69, in infer
    Flownet = LiteFlowNet(args.pretrained_model_liteflownet)
  File "/home/mobax/lpz/Deep-Flow-Guided-Video-Inpainting-master/models/LiteFlowNet_Models/LiteFlowNet.py", line 269, in __init__
    self.load_state_dict(torch.load(model_path))
  File "/home/mobax/anaconda3/envs/lpz/lib/python3.6/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_models/sintel.pth'

**Comment by lukas-blecher** [comment]
Looks like the problem is your Open-CV installation. 
Try reinstalling it or see https://github.com/NVIDIA/nvidia-docker/issues/864#issuecomment-452023152

**Comment by OnlyFlashEobard** [comment]
> Looks like the problem is your Open-CV installation.
> Try reinstalling it or see [NVIDIA/nvidia-docker#864 (comment)](https://github.com/NVIDIA/nvidia-docker/issues/864#issuecomment-452023152)

thanks for your attention,I solve the cv2 problems with your help but after that i get a new issue.

here are error details:
(lpz) mobax@nvidia-quadro-vws-ubuntu-18-1-vm:~/lpz/Deep-Flow-Guided-Video-Inpainting-master$ python tools/video_inpaint.py --frame_dir ./demo/frames --MASK_ROOT ./demo/masks --img_size 512 832 --LiteFlowNet --DFC --ResNet101 --Propagation
This Video has 80 Images
The optical flow list has been generated: ./demo/video_flow.txt
====> Loading ./pretrained_models/sintel.pth
Traceback (most recent call last):
File "tools/video_inpaint.py", line 185, in
main()
File "tools/video_inpaint.py", line 166, in main
extract_flow(args)
File "tools/video_inpaint.py", line 85, in extract_flow
output_file = infer(args)
File "/home/mobax/lpz/Deep-Flow-Guided-Video-Inpainting-master/tools/infer_liteflownet.py", line 69, in infer
Flownet = LiteFlowNet(args.pretrained_model_liteflownet)
File "/home/mobax/lpz/Deep-Flow-Guided-Video-Inpainting-master/models/LiteFlowNet_Models/LiteFlowNet.py", line 269, in init
self.load_state_dict(torch.load(model_path))
File "/home/mobax/anaconda3/envs/lpz/lib/python3.6/site-packages/torch/serialization.py", line 419, in load
f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_models/sintel.pth'

**Comment by lukas-blecher** [comment]
Please see #3
