### ISSUE TITLE
cv2.error ： ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by balablb** [lukas-blecher/Deep-Flow-Guided-Video-Inpainting#7]
I have a problem when using my own data.  I put my frames in  _/demo/sur/frames_  and masks in _/demo/sur/masks_ 

the masks caused the error?

The following is the error message:

This Video has 30 Images
The optical flow list has been generated: ./demo/sur/video_flow.txt
====> Loading /home/xieyl/Deep-Flow-Guided-Video-Inpainting/pretrained_models/network-default.pytorch
100%|███████████████████████████████████████████████████████████████████████████████████████| 58/58 [00:07<00:00,  7.93it/s]

LiteFlowNet Inference has been finished~!
Extracted Flow has been save in ./demo/sur/Flow
Generate datalist for initial step
Flow Completion in First Step
Freezing BatchNorm2D.
Load Pretrained Model from ./pretrained_models/resnet101_movie.pth
  0%|                                                                                                | 0/59 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/video_inpaint.py", line 185, in <module>
    main()
  File "tools/video_inpaint.py", line 169, in main
    flow_completion(args)
  File "tools/video_inpaint.py", line 116, in flow_completion
    test_initial_stage(args)
  File "/home/xieyl/Deep-Flow-Guided-Video-Inpainting/tools/test_scripts.py", line 101, in test_initial_stage
    for i, item in tqdm(enumerate(eval_dataloader), total=len(eval_dataset)):
  File "/home/xieyl/anaconda3/envs/flow/lib/python3.7/site-packages/tqdm/std.py", line 1081, in __iter__
    for obj in iterable:
  File "/home/xieyl/anaconda3/envs/flow/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/xieyl/anaconda3/envs/flow/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
cv2.error: Traceback (most recent call last):
  File "/home/xieyl/anaconda3/envs/flow/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xieyl/anaconda3/envs/flow/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xieyl/Deep-Flow-Guided-Video-Inpainting/dataset/FlowInitial.py", line 78, in __getitem__
    tmp_mask = self._mask_tf(tmp_mask)
  File "/home/xieyl/Deep-Flow-Guided-Video-Inpainting/dataset/FlowInitial.py", line 130, in _mask_tf
    interpolation=cv2.INTER_NEAREST)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by lukas-blecher** [comment]
Hi,
I might have found the issue here.
Try again please.

**Comment by balablb** [comment]
> Hi,
> I might have found the issue here.
> Try again please.


hello ~ read masks correctly (#7) got the same error

**Comment by balablb** [comment]
I found the reason ：The name of the picture must be in this form : 00000.png     ，start from 00000 not 00001 and png not jpg
